(cl:defpackage coordinator-srv
  (:use )
  (:export
   "OPENLOOPNAVSVC"
   "<OPENLOOPNAVSVC-REQUEST>"
   "OPENLOOPNAVSVC-REQUEST"
   "<OPENLOOPNAVSVC-RESPONSE>"
   "OPENLOOPNAVSVC-RESPONSE"
   "COORDINATORSRV"
   "<COORDINATORSRV-REQUEST>"
   "COORDINATORSRV-REQUEST"
   "<COORDINATORSRV-RESPONSE>"
   "COORDINATORSRV-RESPONSE"
  ))

